//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adminn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int food_id { get; set; }
        public string food_name { get; set; }
        public string food_content { get; set; }
        public string food_price { get; set; }
        public string food_link { get; set; }
        public string food_type { get; set; }
    }
}
